#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# aos-alias — one script to manage aliases for bash/zsh/fish
#
# What it does:
#   - Stores aliases in a single TSV registry: name<TAB>command
#   - Renders 3 shell-specific alias files
#   - Optional guided install: sources the files from your shell rc
#   - gum UI when available; CLI works without gum
#
# Files:
#   $XDG_CONFIG_HOME/shell-aliases/aliases.tsv
#   $XDG_CONFIG_HOME/shell-aliases/aliases.bash
#   $XDG_CONFIG_HOME/shell-aliases/aliases.zsh
#   $XDG_CONFIG_HOME/shell-aliases/aliases.fish
#   $XDG_CONFIG_HOME/fish/conf.d/shell-aliases.fish  (symlink)
#
# Quick start:
#   chmod +x ~/bin/aos-alias
#   aos-alias ui
#   aos-alias install
# ============================================================

APP="aos-alias"
CFG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
ROOT_DIR="$CFG_HOME/shell-aliases"
DB="$ROOT_DIR/aliases.tsv"
BASH_FILE="$ROOT_DIR/aliases.bash"
ZSH_FILE="$ROOT_DIR/aliases.zsh"
FISH_FILE="$ROOT_DIR/aliases.fish"
FISH_CONFD_DIR="$CFG_HOME/fish/conf.d"
FISH_CONFD_LINK="$FISH_CONFD_DIR/shell-aliases.fish"

# -------------
# helpers
# -------------
die() { echo "[$APP] $*" >&2; exit 1; }
info() { echo "[$APP] $*" >&2; }

have() { command -v "$1" >/dev/null 2>&1; }

ensure_dirs() {
  mkdir -p "$ROOT_DIR"
  mkdir -p "$FISH_CONFD_DIR"
  touch "$DB"
}

# Quote for bash/zsh single-quoted string: '...'
# Replace each ' with: '"'"'
shell_sq() {
  local s="$1"
  s=${s//\'/\'"\'"\'}
  printf "'%s'" "$s"
}

# Quote for fish using double quotes: "..."
# Escape backslash and double-quote.
fish_dq() {
  local s="$1"
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  printf '"%s"' "$s"
}

valid_name() {
  # shell-safe alias name: letter/_ then letters/digits/_
  [[ "$1" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]
}

# Read DB into stdout (normalized): name<TAB>command, no empties, no comments
read_db() {
  ensure_dirs
  # keep tabs; strip CR; ignore empty and comment lines
  awk -F'\t' 'NF>=2 {name=$1; $1=""; sub(/^\t/,"",$0); cmd=$0; if(name!="" && cmd!="" && name !~ /^#/) print name "\t" cmd}' "$DB" \
    | sed 's/\r$//'
}

write_db_from_stream() {
  # stdin: name<TAB>command
  # sort by name and write atomically
  local tmp
  tmp="$(mktemp)"
  cat \
    | awk -F'\t' 'NF>=2 {print $1"\t"$2}' \
    | sort -t$'\t' -k1,1 \
    > "$tmp"
  mv "$tmp" "$DB"
}

upsert_alias() {
  local name="$1"; shift
  local cmd="$*"
  valid_name "$name" || die "Invalid alias name: $name"
  [[ -n "$cmd" ]] || die "Command cannot be empty"

  read_db \
    | awk -F'\t' -v n="$name" 'BEGIN{OFS="\t"} $1!=n {print $1,$2}' \
    | { cat; printf '%s\t%s\n' "$name" "$cmd"; } \
    | write_db_from_stream

  render_all >/dev/null
  info "Saved alias '$name'"
}

remove_alias() {
  local name="$1"
  valid_name "$name" || die "Invalid alias name: $name"

  read_db \
    | awk -F'\t' -v n="$name" 'BEGIN{OFS="\t"} $1!=n {print $1,$2}' \
    | write_db_from_stream

  render_all >/dev/null
  info "Removed alias '$name'"
}

list_aliases() {
  read_db | awk -F'\t' '{printf "%-20s  %s\n", $1, $2}'
}

render_bash() {
  ensure_dirs
  {
    echo "# Generated by $APP — DO NOT EDIT"
    echo "# Source-of-truth: $DB"
    echo
    read_db | while IFS=$'\t' read -r name cmd; do
      printf 'alias %s=%s\n' "$name" "$(shell_sq "$cmd")"
    done
    echo
  } > "$BASH_FILE"
}

render_zsh() {
  ensure_dirs
  {
    echo "# Generated by $APP — DO NOT EDIT"
    echo "# Source-of-truth: $DB"
    echo
    read_db | while IFS=$'\t' read -r name cmd; do
      printf 'alias %s=%s\n' "$name" "$(shell_sq "$cmd")"
    done
    echo
  } > "$ZSH_FILE"
}

render_fish() {
  ensure_dirs
  {
    echo "# Generated by $APP — DO NOT EDIT"
    echo "# Source-of-truth: $DB"
    echo
    echo "# fish loads *.fish in conf.d automatically."
    echo "# This file is also symlinked into: $FISH_CONFD_LINK"
    echo
    read_db | while IFS=$'\t' read -r name cmd; do
      printf 'alias %s %s\n' "$name" "$(fish_dq "$cmd")"
    done
    echo
  } > "$FISH_FILE"
}

ensure_fish_autoload() {
  ensure_dirs
  if [[ -e "$FISH_CONFD_LINK" || -L "$FISH_CONFD_LINK" ]]; then
    return 0
  fi
  ln -s "$FISH_FILE" "$FISH_CONFD_LINK"
}

render_all() {
  render_bash
  render_zsh
  render_fish
  ensure_fish_autoload
}

append_once() {
  local file="$1" line="$2"
  mkdir -p "$(dirname "$file")"
  touch "$file"
  grep -Fqx "$line" "$file" || echo "$line" >> "$file"
}

install_sources() {
  render_all

  local bashrc="$HOME/.bashrc"
  local zshrc="$HOME/.zshrc"

  local bash_line="[ -f \"$BASH_FILE\" ] && source \"$BASH_FILE\""
  local zsh_line="[ -f \"$ZSH_FILE\" ] && source \"$ZSH_FILE\""

  if have gum; then
    gum style --bold --padding "0 0" "Install: source generated alias files" >/dev/null || true

    if gum confirm "Append source line to $bashrc ?"; then
      append_once "$bashrc" "$bash_line"
      info "Updated $bashrc"
    else
      info "Skipped $bashrc"
    fi

    if gum confirm "Append source line to $zshrc ?"; then
      append_once "$zshrc" "$zsh_line"
      info "Updated $zshrc"
    else
      info "Skipped $zshrc"
    fi

    info "fish: symlink created (autoload) -> $FISH_CONFD_LINK"
  else
    cat <<EOF
[$APP] Install instructions:

Bash  (~/.bashrc):
  $bash_line

Zsh   (~/.zshrc):
  $zsh_line

Fish:
  Symlink for autoload:
    ln -sf "$FISH_FILE" "$FISH_CONFD_LINK"
EOF
  fi
}

# -------------
# gum UI
# -------------
ui_pick_alias() {
  local names
  names="$(read_db | awk -F'\t' '{print $1}')"
  [[ -n "$names" ]] || die "No aliases yet. Use 'add' first."
  printf "%s\n" "$names" | gum choose
}

ui_add() {
  local name cmd
  name="$(gum input --placeholder "alias name (e.g. gs)" --prompt "Name: ")"
  [[ -n "$name" ]] || die "Cancelled"
  valid_name "$name" || die "Invalid alias name: $name"

  cmd="$(gum input --placeholder "command (e.g. git status)" --prompt "Cmd:  ")"
  [[ -n "$cmd" ]] || die "Cancelled"

  upsert_alias "$name" "$cmd"
}

ui_remove() {
  local name
  name="$(ui_pick_alias)"
  [[ -n "$name" ]] || die "Cancelled"
  if gum confirm "Remove alias '$name'?"; then
    remove_alias "$name"
  else
    info "Cancelled"
  fi
}

ui_edit() {
  local name old cmd
  name="$(ui_pick_alias)"
  [[ -n "$name" ]] || die "Cancelled"
  old="$(read_db | awk -F'\t' -v n="$name" '$1==n {print $2; exit}')"

  cmd="$(gum input --value "$old" --prompt "Cmd:  ")"
  [[ -n "$cmd" ]] || die "Cancelled"

  upsert_alias "$name" "$cmd"
}

ui_list() {
  if have gum; then
    read_db | awk -F'\t' '{print $1"\t"$2}' | gum table -w 24,120 -s rounded
  else
    list_aliases
  fi
}

ui_main() {
  have gum || die "gum not found. Install gum OR use CLI mode: add/rm/list/render/install"
  ensure_dirs
  render_all >/dev/null || true

  while true; do
    local choice
    choice="$(printf "%s\n" \
      "Add alias" \
      "Edit alias" \
      "Remove alias" \
      "List aliases" \
      "Render files" \
      "Install source lines" \
      "Quit" \
      | gum choose --header "aos-alias" )"

    case "$choice" in
      "Add alias") ui_add ;;
      "Edit alias") ui_edit ;;
      "Remove alias") ui_remove ;;
      "List aliases") ui_list ;;
      "Render files") render_all; info "Rendered: $BASH_FILE, $ZSH_FILE, $FISH_FILE" ;;
      "Install source lines") install_sources ;;
      "Quit") break ;;
      *) break ;;
    esac
  done
}

# -------------
# CLI
# -------------
usage() {
  cat <<EOF
$APP — multi-shell alias manager (bash/zsh/fish)

Usage:
  $APP ui
  $APP add <name> <command...>
  $APP rm  <name>
  $APP list
  $APP render
  $APP install

Files:
  DB:    $DB
  Bash:  $BASH_FILE
  Zsh:   $ZSH_FILE
  Fish:  $FISH_FILE  (autoload via $FISH_CONFD_LINK)
EOF
}

main() {
  local cmd="${1:-ui}"; shift || true

  case "$cmd" in
    ui) ui_main ;;
    add)
      [[ $# -ge 2 ]] || die "Usage: $APP add <name> <command...>"
      upsert_alias "$1" "${*:2}"
      ;;
    rm|remove|del|delete)
      [[ $# -eq 1 ]] || die "Usage: $APP rm <name>"
      remove_alias "$1"
      ;;
    list|ls)
      list_aliases
      ;;
    render)
      render_all
      info "Rendered: $BASH_FILE, $ZSH_FILE, $FISH_FILE"
      ;;
    install)
      install_sources
      ;;
    help|-h|--help)
      usage
      ;;
    *)
      die "Unknown command: $cmd (try: $APP help)"
      ;;
  esac
}

main "$@"
